export const dummyShops = [
  {
    id: '1',
    name: 'Raj Hair Salon',
    location: 'Sector 18, Noida',
    price: '₹249',
    rating: 4.6,
    category: 'Haircut',
    image: 'https://images.pexels.com/photos/3993449/pexels-photo-3993449.jpeg',
  },
  {
    id: '2',
    name: 'Beard Bros',
    location: 'Sector 62, Noida',
    price: '₹199',
    rating: 4.4,
    category: 'Beard',
    image: 'https://images.pexels.com/photos/3993447/pexels-photo-3993447.jpeg',
  },
  {
    id: '3',
    name: 'Relax Massage Center',
    location: 'Sector 15, Noida',
    price: '₹399',
    rating: 4.7,
    category: 'Massage',
    image: 'https://images.pexels.com/photos/6182267/pexels-photo-6182267.jpeg',
  },
  {
    id: '4',
    name: 'Urban Clippers',
    location: 'Sector 50, Noida',
    price: '₹299',
    rating: 4.5,
    category: 'Haircut',
    image: 'https://images.pexels.com/photos/7697392/pexels-photo-7697392.jpeg',
  },
  {
    id: '5',
    name: 'The Beard Garage',
    location: 'Sector 45, Noida',
    price: '₹179',
    rating: 4.3,
    category: 'Beard',
    image: 'https://images.pexels.com/photos/8972637/pexels-photo-8972637.jpeg',
  },
  {
    id: '6',
    name: 'Soothing Touch Spa',
    location: 'Sector 104, Noida',
    price: '₹499',
    rating: 4.8,
    category: 'Massage',
    image: 'https://images.pexels.com/photos/6621477/pexels-photo-6621477.jpeg',
  },
  {
    id: '7',
    name: 'Trim & Tone',
    location: 'Sector 37, Noida',
    price: '₹349',
    rating: 4.6,
    category: 'Combo Deal',
    image: 'https://images.pexels.com/photos/8436342/pexels-photo-8436342.jpeg',
  },
  {
    id: '8',
    name: 'Snip Masters',
    location: 'Sector 21, Noida',
    price: '₹299',
    rating: 4.5,
    category: 'Haircut',
    image: 'https://images.pexels.com/photos/3993445/pexels-photo-3993445.jpeg',
  },
  {
    id: '9',
    name: 'King’s Beard Spa',
    location: 'Sector 63, Noida',
    price: '₹229',
    rating: 4.4,
    category: 'Beard',
    image: 'https://images.pexels.com/photos/3993446/pexels-photo-3993446.jpeg',
  },
  {
    id: '10',
    name: 'Ayur Bliss Spa',
    location: 'Sector 70, Noida',
    price: '₹549',
    rating: 4.9,
    category: 'Massage',
    image: 'https://images.pexels.com/photos/6621465/pexels-photo-6621465.jpeg',
  },
];

export const categories = [
  { label: 'All', emoji: '🧭' },
  { label: 'Haircut', emoji: '💇' },
  { label: 'Beard', emoji: '🧔' },
  { label: 'Massage', emoji: '💆' },
  { label: 'Combo Deal', emoji: '✂️' },
];

export const banners = [
  {
    id: '1',
    image: 'https://via.placeholder.com/300x150.png?text=Flat+30%25+Off',
  },
  {
    id: '2',
    image: 'https://via.placeholder.com/300x150.png?text=Get+Free+Trim',
  },
  {
    id: '3',
    image: 'https://via.placeholder.com/300x150.png?text=First+Visit+Discount',
  },
];
